import type { DeepQuestion, SimpleQuestion, BranchingQuestion, TrainingQuestion } from "./types";

const course = (lessonNumber: number, lessonTitle: string, section: string) => ({
  lessonNumber,
  lessonTitle,
  section,
  href: `/lesson-${lessonNumber}` as `/lesson-${number}`,
});

const simpleQuestions: SimpleQuestion[] = [
  {
    id: "simple-001-01",
    title: "同事忙碌时适合立即打招呼吗",
    kind: "simple",
    primarySceneId: "scene-1",
    relatedSceneIds: ["scene-2"],
    difficulty: "easy",
    knowledgePoints: ["开口时机", "轻连接"],
    courseReference: course(1, "新人如何自然开口", "开口三问"),
    status: "published",
    version: 1,
    prompt: "入职第一天，你想向邻座同事介绍自己。对方戴着耳机，正在快速回复消息。此时最合适的做法是什么？",
    choices: [
      { id: "a", text: "轻拍对方肩膀，马上完成自我介绍", correct: false, feedback: "突然打断会增加对方压力，也忽略了对方正在忙碌的信号。" },
      { id: "b", text: "先观察，等对方摘下耳机或停下手里的事再开口", correct: true, feedback: "先确认对方是否方便交流，能让第一次连接更自然、压力更小。" },
      { id: "c", text: "不再主动，等对方哪天先和你说话", correct: false, feedback: "等待合适时机不等于放弃行动，可以在对方空闲时主动发出友好信号。" },
    ],
  },
  {
    id: "simple-002-01",
    title: "什么样的同事对话适合加入",
    kind: "simple",
    primarySceneId: "scene-2",
    relatedSceneIds: ["scene-1", "scene-3"],
    difficulty: "easy",
    knowledgePoints: ["话题边界", "入圈三判"],
    courseReference: course(2, "如何加入同事的话题", "入圈三判"),
    status: "published",
    version: 1,
    prompt: "午休时，你想加入同事正在进行的谈话。下面哪种情况最适合自然接话？",
    choices: [
      { id: "a", text: "两人压低声音讨论其中一人的家庭矛盾", correct: false, feedback: "音量、内容和人数都表明这是边界较强的私人对话。" },
      { id: "b", text: "几位同事公开讨论附近新开的餐厅，并看向周围征求推荐", correct: true, feedback: "话题轻、场域开放且存在邀请信号，适合从原话题的一个点接入。" },
      { id: "c", text: "两位同事对着屏幕核对尚未公开的绩效数据", correct: false, feedback: "工作信息具有明显的权限和保密边界，不应为了融入而加入。" },
    ],
  },
  {
    id: "simple-003-01",
    title: "冷场时从哪里找话题",
    kind: "simple",
    primarySceneId: "scene-3",
    relatedSceneIds: ["scene-1", "scene-2"],
    difficulty: "easy",
    knowledgePoints: ["话题种子", "共同环境"],
    courseReference: course(3, "不知道说什么时怎么办", "三颗话题种子"),
    status: "published",
    version: 1,
    prompt: "你和不熟悉的同事一起等会议开始，现场短暂沉默。哪种开场最容易让双方接住？",
    choices: [
      { id: "a", text: "“你为什么一直不说话？”", correct: false, feedback: "这会把自然沉默解释成对方的问题，增加交流压力。" },
      { id: "b", text: "“刚才通知说会议室换到这里，你也是临时赶过来的吗？”", correct: true, feedback: "它来自双方正在经历的共同环境，只放出一个容易回答的问题。" },
      { id: "c", text: "“你对人生最重要的规划是什么？”", correct: false, feedback: "问题过重且需要长篇解释，不适合作为低压力的初始话题。" },
    ],
  },
  {
    id: "simple-004-01",
    title: "一次没被邀请就是排挤吗",
    kind: "simple",
    primarySceneId: "scene-4",
    relatedSceneIds: ["scene-2"],
    difficulty: "medium",
    knowledgePoints: ["排挤三性判断", "事实核验"],
    courseReference: course(4, "如何判断自己是否被排挤", "排挤三性判断法"),
    status: "published",
    version: 1,
    prompt: "你偶然发现三位同事下班后一起吃饭，但没有邀请你。仅根据这一次情况，最合理的判断是什么？",
    choices: [
      { id: "a", text: "这已经足以证明团队在故意排挤你", correct: false, feedback: "单次社交活动无法证明持续性、针对性和实际工作影响。" },
      { id: "b", text: "先不判断动机，继续观察是否持续针对你并影响正常协作", correct: true, feedback: "把感受与结论分开，再检查频率、对比情况和实际影响，更接近事实。" },
      { id: "c", text: "既然没有工作影响，就应当否认自己的失落感", correct: false, feedback: "感到失落是真实体验，但感受本身不能直接证明他人的动机。" },
    ],
  },
  {
    id: "simple-005-02",
    title: "开工前还缺哪类任务信息",
    kind: "simple",
    primarySceneId: "scene-5",
    relatedSceneIds: ["scene-6"],
    difficulty: "medium",
    knowledgePoints: ["任务清晰度三检", "约束确认"],
    courseReference: course(5, "如何确认任务要求", "任务清晰度三检"),
    status: "published",
    version: 1,
    prompt: "领导请你周五前提交一份面向管理层的客户流失分析，并说明要用最近一年的数据。开始分析前，最需要继续确认什么？",
    choices: [
      { id: "a", text: "领导希望使用哪一种字体", correct: false, feedback: "字体通常不是会改变分析方向的开工条件，可以在后续格式确认中处理。" },
      { id: "b", text: "分析要支持什么决策、交付形式和判断完成的标准", correct: true, feedback: "已有范围和时间，但目标、交付与验收标准仍会直接影响分析方法。" },
      { id: "c", text: "领导是否认可你过去做过的所有报告", correct: false, feedback: "这与当前任务的目标、交付和约束无直接关系。" },
    ],
  },
  {
    id: "simple-006-01",
    title: "接单前应检查哪些条件",
    kind: "simple",
    primarySceneId: "scene-6",
    relatedSceneIds: ["scene-5", "scene-9"],
    difficulty: "easy",
    knowledgePoints: ["接单四查"],
    courseReference: course(6, "如何正确接收任务", "接单四查"),
    status: "published",
    version: 1,
    prompt: "你第一次负责客户直播，要求已经明确。正式承诺交付前，哪组检查最完整？",
    choices: [
      { id: "a", text: "只检查自己是否愿意加班", correct: false, feedback: "个人投入意愿不能替代对任务完成条件的系统检查。" },
      { id: "b", text: "检查能力、时间、资源和权限是否足以支持交付", correct: true, feedback: "四项检查能暴露培训、排期、预算、协作者和审批等关键缺口。" },
      { id: "c", text: "只检查领导是否反复强调重要性", correct: false, feedback: "任务重要性不能说明现有条件是否足够完成。" },
    ],
  },
];

const deepQuestions: DeepQuestion[] = [
  {
    id: "deep-001-01",
    title: "入职首日的两次轻连接",
    kind: "deep",
    primarySceneId: "scene-1",
    relatedSceneIds: ["scene-2", "scene-3"],
    difficulty: "medium",
    knowledgePoints: ["开口三问", "自然开口五步法", "回应信号"],
    courseReference: course(1, "新人如何自然开口", "自然开口五步法"),
    status: "published",
    version: 1,
    caseBackground: "你入职第一天，希望认识邻座同事，并在下午向另一个部门的同事请教一个系统入口。你不想显得沉默，也不想给对方造成压力。",
    scenes: [
      {
        id: "node-1",
        context: "上午，邻座同事摘下耳机，伸了个懒腰，暂时没有操作电脑。",
        prompt: "怎样开始最自然？",
        choices: [
          { id: "a", text: "一次介绍完整履历，再问对方的家庭和住址", correct: false, feedback: "信息和问题都过多，第一次交流不需要承担建立亲密关系的任务。" },
          { id: "b", text: "简单介绍自己，再从共同项目问一个轻量问题", correct: true, feedback: "时机合适、话题贴近共同环境，且只给出一个容易接住的问题。" },
          { id: "c", text: "继续等，因为新人不应该主动开口", correct: false, feedback: "此刻已经出现低压力的交流窗口，可以主动发出友好信号。" },
        ],
      },
      {
        id: "node-2",
        context: "下午你向跨部门同事询问系统入口。对方给出链接后只回复“在这里”，随后把视线转回屏幕。",
        prompt: "下一步怎样做？",
        choices: [
          { id: "a", text: "感谢对方并结束交流，之后有具体问题再按范围请教", correct: true, feedback: "对方已经完成回应且发出结束信号，友好收尾能保留下一次协作空间。" },
          { id: "b", text: "马上继续问对方入职多久、负责什么以及午饭去哪吃", correct: false, feedback: "连续扩展话题忽略了对方回到工作的信号。" },
          { id: "c", text: "因为回应简短，判断对方不欢迎新人", correct: false, feedback: "一次简短回应更可能反映当下忙碌，不能直接推导关系态度。" },
        ],
      },
    ],
    summary: "自然开口的目标是完成一次轻连接：观察时机，从共同环境轻问，并根据回应强度继续或收尾。",
  },
  {
    id: "deep-003-01",
    title: "出差同行时让话题自然生长",
    kind: "deep",
    primarySceneId: "scene-3",
    relatedSceneIds: ["scene-1", "scene-2"],
    difficulty: "medium",
    knowledgePoints: ["三颗话题种子", "话题三筛", "适度分享"],
    courseReference: course(3, "不知道说什么时怎么办", "话题生长五步法"),
    status: "published",
    version: 1,
    caseBackground: "你第一次和不熟悉的同事一起去外地拜访客户。候车和乘车时间较长，你希望交流自然一些，但不想把聊天变成采访。",
    scenes: [
      {
        id: "node-1",
        context: "候车时广播通知列车晚点 20 分钟，同事也抬头看了屏幕。",
        prompt: "你可以怎样启动话题？",
        choices: [
          { id: "a", text: "从晚点这个共同经历说起，只问对方是否需要调整客户到达时间", correct: true, feedback: "共同环境提供了安全的话题种子，问题也与双方当前任务有关。" },
          { id: "b", text: "连续询问对方年龄、婚姻、住址和收入", correct: false, feedback: "这些问题缺少共同基础且涉及隐私，容易形成盘问。" },
          { id: "c", text: "为了避免冷场，完整讲述自己过去所有出差经历", correct: false, feedback: "长篇单向表达没有给对方留下容易加入的接口。" },
        ],
      },
      {
        id: "node-2",
        context: "对方回答已经通知客户，并补充自己上次也遇到晚点。你们聊了两句后，对方戴上耳机开始看材料。",
        prompt: "此时最合适的处理是什么？",
        choices: [
          { id: "a", text: "根据“上次”继续追问全部出差细节", correct: false, feedback: "戴耳机和转向材料是明确的注意力变化，应尊重结束信号。" },
          { id: "b", text: "回应一句自己的类似经历，然后说“你先忙，晚点再聊”", correct: true, feedback: "先回应、适度分享并自然结束，既完成交流也保护对方空间。" },
          { id: "c", text: "沉默离开，并认定刚才的话题选择失败", correct: false, feedback: "话题自然结束不代表交流失败，短暂连接本身已经有价值。" },
        ],
      },
    ],
    summary: "没有话题时先从现场寻找种子；一个问题后加入回应和适度分享，并随对方意愿决定继续或结束。",
  },
];

const branchingQuestions: BranchingQuestion[] = [
  {
    id: "branching-002-01",
    title: "加入午餐桌上的多人聊天",
    kind: "branching",
    primarySceneId: "scene-2",
    relatedSceneIds: ["scene-1", "scene-3"],
    difficulty: "medium",
    knowledgePoints: ["听接还模型", "入圈三判", "回应强度"],
    courseReference: course(2, "如何加入同事的话题", "加入话题五步法"),
    status: "published",
    version: 1,
    caseBackground: "你入职第二周，午餐时和几位同事坐在一起。他们正在讨论周末公司附近的活动，你了解其中一个展览。",
    startNodeId: "start",
    nodes: [
      {
        id: "start",
        context: "同事们正轮流分享，当前说话的人还没有讲完。",
        prompt: "你先怎么做？",
        choices: [
          { id: "a", text: "立刻打断，告诉大家你最了解这个展览", correct: false, feedback: "内容相关不等于时机合适，打断会让加入显得像抢夺话题。", nextNodeId: "repair" },
          { id: "b", text: "先听清大家在聊什么，等一句话结束后的空隙", correct: true, feedback: "先听懂原话题并等待自然空隙，是低压力加入的基础。", nextNodeId: "join" },
        ],
      },
      {
        id: "repair",
        context: "被打断的同事停了一下，桌上短暂安静。",
        prompt: "怎样修复更合适？",
        choices: [
          { id: "a", text: "简短道歉，请对方先说完，之后再决定是否补充", correct: true, feedback: "把交流权还给原说话者，能够恢复原有话题秩序。", nextNodeId: "join" },
          { id: "b", text: "为了证明不是故意打断，继续详细解释五分钟", correct: false, feedback: "追加解释会进一步占用话题空间。", nextNodeId: "end" },
        ],
      },
      {
        id: "join",
        context: "有人说“听说那个展览排队很久”，随后看向大家。",
        prompt: "你怎样接话？",
        choices: [
          { id: "a", text: "“我上周去了，下午人少一点。你们是想周末一起去吗？”", correct: true, feedback: "先接住关键词，补充少量相关经历，再用一个问题把交流权还给大家。", nextNodeId: "end" },
          { id: "b", text: "“这都不知道吗？我来给你们完整介绍一下。”", correct: false, feedback: "评价他人并接管话题，会提高群体接纳你的成本。", nextNodeId: "end" },
        ],
      },
      { id: "end", context: "话题继续流动，你已经完成了一次自然加入。", prompt: "本次训练完成。", choices: [], terminal: true },
    ],
    pathSummary: "加入多人话题时先听懂边界和内容，等待空隙，接住一个点，再把交流权还给群体。",
  },
  {
    id: "branching-004-01",
    title: "连续遗漏会议信息后的事实核验",
    kind: "branching",
    primarySceneId: "scene-4",
    relatedSceneIds: ["scene-11", "scene-20"],
    difficulty: "hard",
    knowledgePoints: ["排挤三性判断", "事实四问", "事实核验五步法"],
    courseReference: course(4, "如何判断自己是否被排挤", "事实核验五步法"),
    status: "published",
    version: 1,
    caseBackground: "一个月内，你三次没有收到与自己工作直接相关的临时会议通知，其他项目成员都参加了，导致你两次错过重要信息。",
    startNodeId: "start",
    nodes: [
      {
        id: "start",
        context: "你再次从同事口中得知刚刚开过会，感到自己可能被故意排除。",
        prompt: "第一步应该做什么？",
        choices: [
          { id: "a", text: "在群里质问大家为什么联合排挤你", correct: false, feedback: "在事实尚未核验时直接判断动机会放大冲突。", nextNodeId: "conflict" },
          { id: "b", text: "记录三次事件、通知渠道、参会范围和对工作的实际影响", correct: true, feedback: "先把感受转成可核实的频率、对比和影响，为后续沟通建立事实基础。", nextNodeId: "verify" },
        ],
      },
      {
        id: "conflict",
        context: "同事回应“别想太多，只是忘了”，讨论开始围绕你的情绪展开。",
        prompt: "怎样把沟通拉回问题？",
        choices: [
          { id: "a", text: "说明具体三次遗漏及工作影响，请一起检查通知流程", correct: true, feedback: "回到行为和影响，才能判断是流程缺口还是持续针对。", nextNodeId: "verify" },
          { id: "b", text: "继续要求所有人承认不喜欢你", correct: false, feedback: "他人的内在态度难以验证，也不能直接修复工作信息问题。", nextNodeId: "end" },
        ],
      },
      {
        id: "verify",
        context: "检查后发现，你没有被加入新建的项目日历组；负责人此前不知道这一情况。",
        prompt: "下一步怎样处理？",
        choices: [
          { id: "a", text: "先修复日历组和通知责任，并观察后续是否仍持续遗漏", correct: true, feedback: "目前证据更支持流程问题。先恢复正常协作，再根据后续事实更新判断。", nextNodeId: "end" },
          { id: "b", text: "即使找到流程原因，也坚持这是针对自己的排挤", correct: false, feedback: "新的可核实信息应当用于修正判断，而不是只保留最初解释。", nextNodeId: "end" },
        ],
      },
      { id: "end", context: "通知机制和后续观察方式已经明确。", prompt: "本次训练完成。", choices: [], terminal: true },
    ],
    pathSummary: "判断排挤要检查持续性、针对性和影响性；先记录事实、核实流程、提出请求，再根据后续模式决定是否升级。",
  },
];

export const batch01Questions: TrainingQuestion[] = [...simpleQuestions, ...deepQuestions, ...branchingQuestions];
